language: bash
services: docker

branches:
  only:
    - master

env:
  - VERSION=1.9.0 FOLDER=1.x.x LATEST=true

before_script:
  - env | sort
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  - cd ${FOLDER}
  - image="${DOCKERHUB_USERNAME}/airflow:${VERSION}"
  - latest="${DOCKERHUB_USERNAME}/airflow:latest"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build --build-arg VERSION=${VERSION} -t "$image" .
      ../test/run-tests.sh "$image"
      docker push "$image"
      if [ "$LATEST" == "true" ]; then
        docker tag "$image" "$latest"
        docker push "$latest" 
      fi
    )


after_script:
  - docker images