version: '3.5'
services:
    airflow-scheduler:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - redis
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: redis
            CELERY_BROKER_HOST: redis
            CELERY_BROKER_PORT: 6379
            INITDB: "True"
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow scheduler
    airflow-webserver:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - redis
        ports:
            - 8180:8080
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: redis
            CELERY_BROKER_HOST: redis
            CELERY_BROKER_PORT: 6379
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    airflow-worker:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - redis
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: redis
            CELERY_BROKER_HOST: redis
            CELERY_BROKER_PORT: 6379
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow worker
    airflow-flower:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - redis
        ports:
            - 5555:5555
        networks:
            - airflow
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: redis
            CELERY_BROKER_HOST: redis
            CELERY_BROKER_PORT: 6379
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow flower
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        networks: 
            - airflow
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            MYSQL_USER: airflow
            MYSQL_PASSWORD: yey123456
            MYSQL_DATABASE: airflow
            MYSQL_ROOT_PASSWORD: iamroot321654
    redis:
        image: redis:3.2
        networks:
            - airflow
networks:
    airflow: