version: '3.5'
services:
    airflow-scheduler:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - rabbitmq
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            BACKEND: mysql
            EXECUTOR: CeleryExecutor
            MYSQL_USER: airflow
            MYSQL_PASSWORD: yey123456
            MYSQL_DATABASE: airflow
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            RABBITMQ_USER: airflow
            RABBITMQ_PASSWORD: yey123456
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            INITDB: "True"
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow scheduler
    airflow-webserver:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - rabbitmq
        ports:
            - 8180:8080
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            BACKEND: mysql
            EXECUTOR: CeleryExecutor
            MYSQL_USER: airflow
            MYSQL_PASSWORD: yey123456
            MYSQL_DATABASE: airflow
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            RABBITMQ_USER: airflow
            RABBITMQ_PASSWORD: yey123456
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_PORT: 5672
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    airflow-worker:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - rabbitmq
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            EXECUTOR: CeleryExecutor
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow worker
    airflow-flower:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - mysql
            - rabbitmq
        ports:
            - 5555:5555
        networks:
            - airflow
        environment:
            EXECUTOR: CeleryExecutor
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow flower
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        networks: 
            - airflow
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            MYSQL_USER: airflow
            MYSQL_PASSWORD: yey123456
            MYSQL_DATABASE: airflow
            MYSQL_ROOT_PASSWORD: iamroot321654
    rabbitmq:
        image: rabbitmq:3.7.3
        environment:
            RABBITMQ_DEFAULT_USER: airflow
            RABBITMQ_DEFAULT_PASS: yey123456
networks:
    airflow: