version: '3.5'
services:
    airflow-scheduler:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - postgres
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            BACKEND: postgres
            EXECUTOR: LocalExecutor
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: postgres
            BACKEND_PORT: 5432
            INITDB: "True"
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow scheduler
    airflow-webserver:
        image: z0beat/airflow:1.9.0
        depends_on: 
            - postgres
        ports:
            - 8180:8080
        networks:
            - airflow
        volumes:
            - ${AIRFLOW_DAGS}:/opt/airflow/dags
        environment:
            BACKEND: postgres
            EXECUTOR: LocalExecutor
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: postgres
            BACKEND_PORT: 5432
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    postgres:
        image: postgres:10.2
        ports:
            - 5432:5432
        networks: 
            - airflow
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: yey123456
            POSTGRES_DB: airflow

networks:
    airflow: