kind: Service
apiVersion: v1
metadata:
  name:  redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name:  redis
    port:  6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2
          ports:
            - name: redis
              containerPort: 6379