kind: Service
apiVersion: v1
metadata:
  name:  airflow
spec:
  selector:
    app: airflow
    svc: webserver
  type: NodePort
  ports:
  - name:  webserver
    port:  8080
    targetPort:  webserver
  - name: flower
    port: 5555
    targetPort: flower
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        svc: webserver
        version: 1.9.0
    spec:
      volumes:
        - name: airflow-dags
          hostPath:
            path: /projects/airflow-for-docker/airflow-dags
            type: Directory
      containers:
        - name: webserver
          image: z0beat/airflow:1.9.0
          args: ["airflow", "webserver"]
          ports:
            - name: webserver
              containerPort: 8080
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
              readOnly: true
          env:
            - name: BACKEND
              value: mysql
            - name: EXECUTOR
              value: CeleryExecutor
            - name: BACKEND_USER
              value: airflow
            - name: BACKEND_PASSWORD
              value: yey123456
            - name: BACKEND_DATABASE
              value: airflow
            - name: BACKEND_HOST
              value: mysql
            - name: BACKEND_PORT
              value: "3306"
            - name: BROKER
              value: redis
            - name: CELERY_BROKER_HOST
              value: redis
            - name: CELERY_BROKER_PORT
              value: "6379"
            - name: FERNET_KEY
              value: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        - name: scheduler
          image: z0beat/airflow:1.9.0
          args: ["airflow", "scheduler"]
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
              readOnly: true
          env:
            - name: BACKEND
              value: mysql
            - name: EXECUTOR
              value: CeleryExecutor
            - name: BACKEND_USER
              value: airflow
            - name: BACKEND_PASSWORD
              value: yey123456
            - name: BACKEND_DATABASE
              value: airflow
            - name: BACKEND_HOST
              value: mysql
            - name: BACKEND_PORT
              value: "3306"
            - name: INITDB
              value: "True"
            - name: BROKER
              value: redis
            - name: CELERY_BROKER_HOST
              value: redis
            - name: CELERY_BROKER_PORT
              value: "6379"
            - name: FERNET_KEY
              value: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        - name: flower
          image: z0beat/airflow:1.9.0
          args: ["airflow", "flower"]
          ports:
            - name: flower
              containerPort: 5555
          env:
            - name: BACKEND
              value: mysql
            - name: EXECUTOR
              value: CeleryExecutor
            - name: BACKEND_USER
              value: airflow
            - name: BACKEND_PASSWORD
              value: yey123456
            - name: BACKEND_DATABASE
              value: airflow
            - name: BACKEND_HOST
              value: mysql
            - name: BACKEND_PORT
              value: "3306"
            - name: BROKER
              value: redis
            - name: CELERY_BROKER_HOST
              value: redis
            - name: CELERY_BROKER_PORT
              value: "6379"
            - name: FERNET_KEY
              value: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-workers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        svc: worker
        version: 1.9.0
    spec:
      volumes:
        - name: airflow-dags
          hostPath:
            path: /projects/airflow-for-docker/airflow-dags
            type: Directory
      containers:
        - name: worker
          image: z0beat/airflow:1.9.0
          args: ["airflow", "worker"]
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
              readOnly: true
          env:
            - name: BACKEND
              value: mysql
            - name: EXECUTOR
              value: CeleryExecutor
            - name: BACKEND_USER
              value: airflow
            - name: BACKEND_PASSWORD
              value: yey123456
            - name: BACKEND_DATABASE
              value: airflow
            - name: BACKEND_HOST
              value: mysql
            - name: BACKEND_PORT
              value: "3306"
            - name: BROKER
              value: redis
            - name: CELERY_BROKER_HOST
              value: redis
            - name: CELERY_BROKER_PORT
              value: "6379"
            - name: FERNET_KEY
              value: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=